// <auto-generated />
using System;
using Konyvtar_nyilvantarto.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konyvtar_nyilvantarto.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20230518211036_NewInit")]
    partial class NewInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Konyvtar_nyilvantarto.Services.BorrowingData.Model.BorrowingDataEntity", b =>
                {
                    b.Property<Guid>("BorrowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowingDataBookEntityFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowingDataLibraryMembersFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RentalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RetrievalLimitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("BorrowingId");

                    b.HasIndex("BorrowingDataBookEntityFK")
                        .IsUnique();

                    b.HasIndex("BorrowingDataLibraryMembersFK")
                        .IsUnique();

                    b.ToTable("BorrowingData");
                });

            modelBuilder.Entity("LibaryRegister.Contracts.Book.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfPublication")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibaryRegister.Contracts.LibraryMember.LibraryMemberEntity", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("LibraryMembers");
                });

            modelBuilder.Entity("Konyvtar_nyilvantarto.Services.BorrowingData.Model.BorrowingDataEntity", b =>
                {
                    b.HasOne("LibaryRegister.Contracts.Book.BookEntity", "Book")
                        .WithOne("BorrowingData")
                        .HasForeignKey("Konyvtar_nyilvantarto.Services.BorrowingData.Model.BorrowingDataEntity", "BorrowingDataBookEntityFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibaryRegister.Contracts.LibraryMember.LibraryMemberEntity", "LibraryMembers")
                        .WithOne("BorrowingData")
                        .HasForeignKey("Konyvtar_nyilvantarto.Services.BorrowingData.Model.BorrowingDataEntity", "BorrowingDataLibraryMembersFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("LibraryMembers");
                });

            modelBuilder.Entity("LibaryRegister.Contracts.Book.BookEntity", b =>
                {
                    b.Navigation("BorrowingData");
                });

            modelBuilder.Entity("LibaryRegister.Contracts.LibraryMember.LibraryMemberEntity", b =>
                {
                    b.Navigation("BorrowingData");
                });
#pragma warning restore 612, 618
        }
    }
}
